name: 'AWS-CodePipeline-Trigger'
description: 'Action that triggers an aws pipeline code. To do this, you need an AWS account (AWS id and key) and a pipeline created on AWS (pipeline name). '
author: '@pgrandieres'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'flag'
  color: 'red'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
