name: 'Trigger AWS CodePipeline'
description: 'Action that triggers an aws pipeline code.'
author: '@pgrandieres'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'flag'
  color: 'red'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
